alias ls='ls -F'
alias m='make'
alias mi='make install'

alias camera='cd $C'
alias soapui='sh ~/local/soapui-4.5.1/bin/soapui.sh'
alias smartsvn='sh ~/local/smartsvn-6_0_9/bin/smartsvn.sh'
alias ombranch='ombuild -Dboard=A1 -Dproduct=9083 -Dopsys=linux -Darch=dm644x -Ddebug=false'

alias otbuild='ombuild -Dproduct=9083 -Darch=dm644x -Dopsys=linux -Dboard=A1 -propertyfile "/mnt/wormhole/home/paula/omons-dev/imaging-products/odyssey/9083/trunk/build.conf"'

alias dfly='cd /home/paula/work/dragonfly'
alias max='cd /home/paula/work/omons-mhorn'
alias authos='cd $O/omons/authos'
alias licapp='cd $O/omons/licapp'
alias deimos='cd $O/omons/deimos'
alias fuzz='cd $O/omons/fuzz'
alias mariner='cd $O/omons/mariner'
alias mcp='cd $O/omons/mcp'
alias phobos='cd $O/omons/phobos'
alias mariner='cd $O/mhorn/mariner2'
alias encom='cd $O/omons/encom'
alias tharsis='cd $O/omons/tharsis'
alias apps='cd $O/omons'
alias omons='cd $O/omons/omons'
alias newui='cd $O/mhorn/onvifwebui'
alias jovis='cd $O/mhorn/jovis'
alias get=git
alias cleanit='sudo git clean -xffd;git reset --hard'

alias ob='ombuild build'
alias oi='ombuild install'

alias git_branch_age='for k in `git branch -a |perl -pe s/^..//`;do echo -e `git show --pretty=format:"%Cgreen%ci %Cblue%cr%Creset" $k|head -n 1`\\t$k;done|sort -r'
alias precache9='ombuild -f publish.xml depends configure install -Dboard=A0 -Drev.branch=staging_9280_2.0.0_BLD.0.0'
alias distclean9='ombuild -propertyfile /mnt/wormhole/home/paula/work/staging9280/products/9280/build.conf distclean'
alias config9='ombuild -propertyfile /mnt/wormhole//home/paula/work/staging9280/products/9280/build.conf configure -Dboard=A0'
alias precache8='ombuild -f publish.xml depends configure install -Dboard=A0 -Drev.branch=develop_BLD'
alias distclean8='ombuild -propertyfile /mnt/wormhole/$O/products/8280/build.conf distclean'
alias config8='ombuild -propertyfile /mnt/wormhole/$O/products/8280/build.conf configure -Dboard=A0'

alias sclean='sebu distclean -p 8280'
alias sconfigure='sebu sconfigure -p 8280'
alias sbuild='sebu build -p 8280'
alias sinstall='sebu install -p 8280'

alias mhorn='cd $O/mhorn'
alias pcp2='cd $O/mhorn/pcp2'

alias mytest='cd $B/Private/Test/Triggers'
alias bom='cd $B/src/Models/BasicObjModel'
alias geo='cd $B/src/Models/Geom'
alias blm='cd $B/src/Models/Layout'
alias bcm='cd $B/src/Models/Connectivity'
alias bsl='cd $B/src/Models/StructuredLayout'
alias dm='cd $B/src/Models/DesignMgmt'
alias gr='cd $B/src/Models/Graph'
alias dash='cd /data/Badger/plugins/pinpoint_core'
alias dsh='cd /data/Badger/src/Tools/Dashboard'
alias dshs='cd /data/Badger/src/Tools/Dashboard/Server'
alias dshd='cd /data/Badger/src/Tools/Dashboard/Database'
alias dshm='cd /data/Badger/src/Tools/Dashboard/Models'
alias js='cd /data/Badger/js/Tuscany'
alias css='cd /data/Badger/css/Tuscany'
alias tmpl='cd /data/Badger/etc/www/templates'
alias ol='cd /data/Badger/js/OpenLayers/Tuscany'
alias www='cd /data/Badger/etc/www'
alias pp='cd /data/Badger/src/Tools/Dashboard'
alias rdb='rm -rf DBS'
alias temp='cd /data/Badger/etc/www/templates'
alias btest='cd /data/BadgerTest/Dashboard'

alias bslu='cd $B/src/Util/StructuredLayout'
alias blmu='cd $B/src/Util/Layout'
alias geou='cd $B/src/Util/Geom'
alias bcmu='cd $B/src/Util/Connect'
alias guiu='cd $B/src/Util/UI'

alias bslf='cd $B/src/Util/Find/StructuredLayout'
alias blmf='cd $B/src/Util/Find/Layout'
alias geof='cd $B/src/Util/Find/Geom'
alias bcmf='cd $B/src/Util/Find/Connect'

alias bslg='cd $B/src/UI/StructuredLayout'
alias blmg='cd $B/src/UI/Layout'
alias geog='cd $B/src/UI/Geom'

alias splat='cd $B/src/UI/StructuredLayout'
alias goperl='cd $B/scripts/plugins'
alias layout='cd $B/src/UI/Layout'
alias geom='cd $B/src/UI/Geom'
alias gui='cd $B/src/UI/Primitives'

alias icons='cd $B/etc/icons'
alias include='cd $B/include'
alias src='cd $B/src'
alias badger='cd $B'
alias qt='cd /data/SupportTools/trunk/src/qt-x11-opensource-src-4.5.1'

alias etc='cd $B/etc'
export doc=/data/Badger/doc/private/Tegola/NewDocumentation
alias alu='cd $B/examples/alu-cf'
alias aos='cd $B/examples/aos'
alias wire='cd $B/src/UI/Tools/WireEdit'
alias eco='cd $B/src/Tools/ECO'
alias ecog='cd $B/src/UI/Tools/ECO'
alias ecoe='cd $B/src/ExtLang/ECO'
alias giro='cd $B/src/UI/Tools/Giro'

#alias apps='cd /data/apps/trunk/static'
alias nvidia='cd /data/nvidia/svn/perl'

alias demo='cd /data/apps/trunk/static/dac/2008/stelvio'
alias azul='cd /data/apps/trunk/static/tda/dashboard/examples/azul'
alias t3='cd /data/Badger/Private/Test/Pinpoint/testcase3'
alias dac='cd /data/Badger/Private/Test/Pinpoint/dac'
alias stream='cd /data/Badger/Private/Test/Pinpoint/stream2.0'
alias sand='cd /data/apps/trunk/static/Sandcraft/'
alias xi='cd /data/apps/trunk/static/xilinx/dsp'


alias ungold='gunzip < Golden.xml > Golden.out'
alias untest='gunzip < TestResults.xml > TestResults.out'
alias fix_map='xmodmap ~/.xmodmap'
alias awk-grep='ack-grep -i'

alias omv='omverse -b /mnt/wormhole/`pwd`'
